Check xml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,13 +17,45 @@ permissions:
   contents: read
   pages: write
   id-token: write
+  pull-requests: write  # Required to comment on PRs
   
 concurrency:
   group: 'pages'
-  cancel-in-progress: true
+  cancel-in-progress: False
 
 jobs:
+  parse_appfilter:
+    if: github.event_name == 'pull_request_target'
+    runs-on: ubuntu-latest
+    env:
+      failure: true
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Validate appfilter.xml
+        id: validate
+        run: |
+          if ! PARSE_OUTPUT=$(xmllint --noout newicons\appfilter.xml 2>&1); then
+            echo "Parsing appfilter.xml failed."
+            echo "failure=true" >> $GITHUB_ENV
+            exit 1
+          else
+            echo "Parsing succeeded."
+            echo "failure=false" >> $GITHUB_ENV
+          fi
+
+      - name: Post failure comment to PR
+        if: env.failure == 'true'
+        run: |
+          gh pr comment ${{ github.event.pull_request.number }} --body "Parsing of 'newicons/appfilter.xml' failed. Please fix the XML syntax errors. \n\`\`\`\n$PARSE_OUTPUT\n\`\`\`"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   parse_and_combine:
+    if: (github.event_name == 'push') || (github.event_name == 'pull_request_target' && needs.parse_appfilter.result == 'success')
+    needs: parse_appfilter
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
